// React/app-basicos/src/Components/Bucles/Bucles.jsx
import './Bucles.scss'

const Bucles = ({}) => {
    
    let semana = [ 'lunes' , 'martes' , 'miércoles' ];

    let clase = [
        { id : 0 , nombre : "Emma" },
        { id : 1 , nombre : "Timmy" },
        { id : 2 , nombre : "John" },
        { id : 3 , nombre : "Elva" }
    ]
    
    return (
        <div className="Bucles">
            <h1>Soy Bucles</h1>

            <ul>
                {
                    semana.map( ( cadaDia , i ) => <li key={i}>{ cadaDia }</li>)
                }
            </ul>

            <ul>
                {
                    semana.map( ( cadaDia , i ) => <li key={i}>{ cadaDia }</li>)
                }
            </ul>

            <ul>
                {
                    semana.map( ( cadaDia , i ) => <li key={i}>{ cadaDia }</li>)
                }
            </ul>

            <ul>
                {
                    semana.map( ( cadaDia , i ) => <li key={i}>{ cadaDia }</li>)
                }
            </ul>

            <ul>
                {
                    semana.map( ( cadaDia , i ) => <li key={i}>{ cadaDia }</li>)
                }
            </ul>

            <ul>
                {
                    clase.map( alumno => <li key={alumno.id}>{ alumno.nombre}</li>)
                }
            </ul>

            <ul>
                {
                    clase.map( alumno => <li key={alumno.id}>{ alumno.nombre }</li>)
                }
            </ul>

            <ul>
                {
                    clase.map( alumno => <li key={alumno.id}>{ alumno.nombre }</li>)
                }
            </ul>


        </div>
    )
}

export default Bucles;

// Angular/Angular-App-Efectos/src/app/componentes/bucles/bucles.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bucles',
  templateUrl: './bucles.component.html',
  styleUrls: ['./bucles.component.scss']
})
export class BuclesComponent implements OnInit {

  semana : string[] = [
    'lunes', 'martes', 'miércoles'
  ]

  clase = [
    { nombre : 'Timmy'    , apellido : 'Anderson'   },
    { nombre : 'John'     , apellido : 'Wick'       },
    { nombre : 'María'    , apellido : 'Valenzuela' },
    { nombre : 'Vladimir' , apellido : 'Putin'      },
  ]

  constructor() { }

  ngOnInit(): void { }

}


<ul>
    <li *ngFor=" let dia of semana; let i = index ">
        {{ dia }}
        {{ i }}
    </li>
</ul>

<ul>
    <li *ngFor=" let alumno of clase ">
        {{ alumno.nombre }}
        {{ alumno.apellido }}
    </li>
</ul>
